version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    target_branch: "dev"
    automerged_updates:
      - match:
          dependency_type: "all"
    default_labels:
      - "dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
