name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: bash ./gradlew build
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Lint
        run: bash ./gradlew lint --stacktrace
